on:
 workflow_dispatch:
jobs:
  install-mpv:
    runs-on: ubuntu-latest
    steps:
      - name: Install mpv via APT
        run: |
          sudo apt-get update
          sudo apt-get install -y mpv
          
      - name: Verify installation
        run: |
          mpv --version
          which mpv
