on:
 workflow_dispatch:
jobs:
  install-mpv:
    runs-on: ubuntu-latest
    steps:
      - name: Install mpv via APT
        run: sudo apt-get install -y mpv
          
      - name: Verify installation
        run: mpv "https://youtu.be/xmN7oz75rKA"
