name: First Workflow

on:
   push:
      branches:
        - master
jobs:
   examble:
     runs-on: ubuntu-latest 
     steps:
       - name : print welcome massage
         run: echo "welcome"

       - name : checkout-repo
         uses: actions/checkout@v5.0.0
         
       - name : the List
         run: ls -la
         
  
